theme = "slick"
icons = "material-nf"
icons_format= " <span font_family='Hack NF'>{icon}</span> "

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block="music"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "net"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "temperature"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "nvidia_gpu"

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu"
interval = "once"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
