icons_format= " <span font_family='Hack NF'>{icon}</span> "

[theme]
theme = "slick"
[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_w:60) |"

[[block]]
block="music"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "net"

[[block]]
block = "cpu"
interval = 1
format = "$utilization $frequency "

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "k10temp-*"

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) "

[[block]]
block = "nvidia_gpu"

[[block]]
block = "sound"

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
confirm_msg = "Are you sure you want to suspend?"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
[[block.items]]
display = " -&gt;  Logout   &lt;-"
cmd = "gnome-session-quit"


[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %m/%d %R') "
short = " $icon $timestamp.datetime(f:%R) "
