icons_format= " <span font_family='Monaspace Neon'>{icon}</span> "

[theme]
theme = "slick"
[icons]
icons = "material-nf"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %m/%d %R') "
short = " $icon $timestamp.datetime(f:%R) "
